### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by shoaibsharif** [fivethree-team/nestjs-prisma-starter#159]
When I am trying to run `docker-compose up` I get this error:
```sh
Step 4/10 : COPY ./prisma/schema.prisma ./
ERROR: Service 'nest-api' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder161410517/prisma/schema.prisma: no such file or directory
```
I am using Docker in Mac. I have also tried the same with my `RockPro64` server runs on `Ubuntu 18.04`. still having the same issue.

**Comment by marcjulian** [comment]
Hi @shoaibsharif I assume you are on the prisma2 branch? I got the same error as you. Seems like `prisma` dir was still in `.dockerignore`. I removed it from dockerignore and now `docker-compose up` should build the nest-api.

Did this fix your issue?
