### ISSUE TITLE
Cannot run after upgrading to @nestjs/graphql v7

### ISSUE THREAD

**Issue by sessionboy** [fivethree-team/nestjs-prisma-starter#243]
After upgrading to `@nestjs/graphql v7`,  the schema generated by `@nestjs/graphql v7` is not compatible with the schema generated by prisma

**Comment by marcjulian** [comment]
@sessionboy Hi did you check out the [migration guide](https://docs.nestjs.com/migration-guide)?

**Comment by marcjulian** [comment]
What is your issue? Can you provide a reproduction repository?

**Comment by marcjulian** [comment]
I added a branch for v7 you can check it out. Maybe this helps you https://github.com/fivethree-team/nestjs-prisma-starter/tree/feature/migrate-nest-7

**Comment by sessionboy** [comment]
@marcjulian  Thanks, now i know what to do.
