### ISSUE TITLE
Feature Request: Social Logins

### ISSUE THREAD

**Issue by kodeine** [fivethree-team/nestjs-prisma-starter#304]
as the title says.

**Comment by marcjulian** [comment]
@kodeine feel free to provide a PR for your favorite Social Login.

**Comment by yassinebridi** [comment]
@kodeine have you figure out a way to do this?

**Comment by shafikhaan** [comment]
@yassinebridi @kodeine have you guys figured it out?

**Comment by yassinebridi** [comment]
Yes, but i can't atm, i will post it when i have time.

**Comment by yassinebridi** [comment]
I will create a repo, and post it here, feel free to add a PR to this repo.

**Comment by shafikhaan** [comment]
@yassinebridi awesome, will add PR in here

**Comment by shafikhaan** [comment]
@yassinebridi any news on social logins?

**Comment by yassinebridi** [comment]
@shafikhaan Sorry for the late answer, here is a starter repo, there is no documentation at the moment, so you need to dig in.
https://github.com/yassinebridi/nestjs-oauth-starter
If you have found some problems, feel free to create an issue.
