### ISSUE TITLE
Feature Request: replace type-graphql with  nexus-graphql, CODE-FIRST

### ISSUE THREAD

**Issue by ZiNai** [fivethree-team/nestjs-prisma-starter#329]
I feel this Prisma + [nexus](https://github.com/graphql-nexus/nexus) is better, can there be a CODE-FIRST second method, or integration?

**Comment by marcjulian** [comment]
@ZiNai i tried nexus with nestjs and here is the repo https://github.com/marcjulian/nestjs-prisma-nexus

At the moment, I think code first approach from Nest is better integrated with Nest ecosystem than nexus.

**Comment by ZiNai** [comment]
> @ZiNai i tried nexus with nestjs and here is the repo https://github.com/marcjulian/nestjs-prisma-nexus
> 
> At the moment, I think code first approach from Nest is better integrated with Nest ecosystem than nexus.

@marcjulian Thank you very much. I read the repo you provided, and studied the documentation of nexus, and found that it is more like a 'toy' at present, and it can not be combined with the characteristics of typescript.
And it is very difficult for the application specific to the business to do field verification and deal with more business-specific details.

**My ideal state** is to be able to directly generate dto and model with type-graphql decorator partial business from prisma's schema. There is similar code in @prisma/client. You may need to customize his schema generator. Even basic CURD can be generated templated. Similar to prisma schema =>type-graphql

This should make better use of the features of prisma and nestjs, combining CODE-FIRST and SCHEMA-FIRST

**Finally**, thank you again for your efforts. I have applied _nestjs-prisma-starter_ to my work, although this is a bit technically aggressive, I look forward to more new features

**Comment by marcjulian** [comment]
Maybe the upcoming integration if prisma with type-graphql, see [476](https://github.com/MichalLytek/type-graphql/issues/476), is what you are looking for. 

Type-graphql also provides a [nestjs](https://github.com/MichalLytek/typegraphql-nestjs) module, which is still under development, which we can use together with the prisma integration.

**Comment by marcjulian** [comment]
New features are always welcome 💯
