### ISSUE TITLE
Rest api version

### ISSUE THREAD

**Issue by dpyzo0o** [fivethree-team/nestjs-prisma-starter#395]
Hi, the example is using graphql, is threre an example showing how to integrate nestjs with prisma2 using rest api?

**Comment by marcjulian** [comment]
@dpyzo0o here is an example how to use prisma2 with rest api. https://notiz.dev/blog/how-to-connect-nestjs-with-prisma#step-8-query-data-model

You can inject the `PrismaService` in your Rest controllers or other services

**Comment by dpyzo0o** [comment]
@marcjulian Thanks!

**Comment by marcjulian** [comment]
@dpyzo0o you welcome, let me know if you have any further question
