### ISSUE TITLE
what the purpose of schema.prisma file and the model file.?

### ISSUE THREAD

**Issue by skanel** [fivethree-team/nestjs-prisma-starter#445]
i some confuse, could please explain

1. in `schema.prisma` file what is the purpose of this file
2. why  we have the mode file while we have defined table definition. in `schema.prisma` already.

thanks

**Comment by marcjulian** [comment]
@skanel I wrote about the differences https://github.com/fivethree-team/nestjs-prisma-starter/issues/427#issuecomment-721636375. Hope this helps clarifying the differenc.

**Comment by marcjulian** [comment]
I have moved this topic into Dicussions https://github.com/fivethree-team/nestjs-prisma-starter/discussions/446

**Comment by skanel** [comment]
thanks @marcjulian
