### ISSUE TITLE
Getting Started: Error querying the database: db error: FATAL: role "prisma" does not exist

### ISSUE THREAD

**Issue by joshsny** [fivethree-team/nestjs-prisma-starter#447]
I am completely new to both NestJS and Prisma so forgive me if I am making a silly mistake. 🤦 

I've run through the instructions a couple of times and can't seem to get past Step 3.

To reproduce:

```
git clone https://github.com/fivethree-team/nestjs-prisma-starter
cd nestjs-prisma-starter
npm install
cp example.env .env 
npm run docker:db
npm run migrate:dev
```

Which results in the following error: Error querying the database: db error: FATAL: role "prisma" does not exist

**Comment by marcjulian** [comment]
Hey @joshsny can you add the whole logs when you run `npm run migrate:dev`?

- `npm run docker:db` creates a PostgreSQL DB Docker container
- `npm run migrate:dev` applies the migration to the Postgre DB (in docker), if the database is not available this command should create the database and the postgres user is called `prisma`

It might be that the database is not correctly created by docker.

By the which node version are you using?
