### ISSUE TITLE
seeding doent work

### ISSUE THREAD

**Issue by aswinsegwitz** [fivethree-team/nestjs-prisma-starter#453]

**Comment by marcjulian** [comment]
Do you have some more information? Error message? Which prisma version are you using?

For me `npx prisma db seed --preview-feature` works just fine.

**Comment by mariuswallin** [comment]
I resolved by npx prisma migrate dev

and update package.json with this

"prisma": {
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
  }

**Comment by marcjulian** [comment]
Yes that is necessarcy since `prisma@3.0.2`
