### ISSUE TITLE
JWT Refresh Token

### ISSUE THREAD

**Issue by marcjulian** [fivethree-team/nestjs-prisma-starter#59]

**Comment by leohxj** [comment]
new feature?

**Comment by marcjulian** [comment]
@leohxj Do you mind preparing a PR for this feature?

**Comment by leohxj** [comment]
@marcjulian Yeah I will try and do that.

**Comment by leohxj** [comment]
Should we need to import Redis to record refresh_token(expire data)?

When user interactive, we update the refresh_token (for example, current time + 7 days), and user only need login again when they have no interactive more than 7 days?

**Comment by marcjulian** [comment]
@leohxj I think we can use the @nest/jwt package for implementing the refresh token.

Right now we can get the `accessToken` from authenticating and login. The `accessToken` should be short-lived with an early expiration date. Additionally to the `accessToken` we should generate a `refreshToken` which also expire but live longer. 

Then we need a new endpoint e.g. `/token` where we use the `refreshToken` to get a new `accessToken`.

You can have a look here for a good description https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/ 

That said, there are always more ways on how to implement this, maybe even with Redis but this will add additional complexitiy to the starter.

**Comment by leohxj** [comment]
@marcjulian get it.
Generate refresh_token which has longer expire time, and add a mutation like below: 
```
token(refreshToken: String!) { 
  accessToken: Sting
  refresh_token: String
}
```
to generate the new token.

**Comment by leohxj** [comment]
@marcjulian new PR is submit, do you have time to code review? thanks.
